### ISSUE TITLE
[Bug] 使用UMD版本，本地运行调试正常，发布后有报错，且表格无法输入内容

### ISSUE THREAD

**Issue by yyyyffqqqq** [dream-num/univer#1340]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

UMD版本

### 复现链接

<img width="1434" alt="截屏2024-02-06 14 11 43" src="https://github.com/dream-num/univer/assets/19225441/dcb1db2b-1705-46a9-9736-f7c439c11b62">

### 预期行为

可以输入表格内容

### 实际行为

初始化表格就报错，可以显示表格，但输入不了内容（使用http协议发布的网站）

### 运行环境

Chrome

**Comment by Dushusir** [comment]
复现步骤再详细一点，最好能提供在线DEMO

**Comment by jikkai** [comment]
It seems that you have not imported `@univerjs/docs` or have made a mistake in the order of import.
This is not a bug, so we will close this issue.
If you believe that the issue is not caused by the reasons mentioned above, please try to reproduce the problem using this [online demo](https://stackblitz.com/~/github.com/awesome-univer/sheets-umd-demo), and feel free to reopen this issue at any time.
