### ISSUE TITLE
[Feature] Sometimes it is necessary to load data in batches, but I see that there is no API for data update in the worksheet. Is this function possible

### ISSUE THREAD

**Issue by percentcola3** [dream-num/univer#4039]
### 初始清单

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 问题

If there are 1,000 pieces of data in total, each time the backend is requested, only 200 pieces can be requested at a time, so multiple requests are required.
Each time the request ends, data needs to be added to the sheet page.

I had commit an ISSUE ：https://github.com/dream-num/univer/issues/4012。
But I  can not find which API  in  FWorksheet  llist，could do this thing. https://univer.ai/typedoc/@univerjs/facade/classes/FWorksheet

**Comment by jikkai** [comment]
Hi @percentcola3,

I understand you have further questions. However, instead of creating a new, duplicate issue, please continue the discussion in the original issue thread.  Creating redundant issues is considered inefficient and can even be seen as a misuse of resources.

As I mentioned in #4012, you should use the Facade APIs under FWorksheet. The standard procedure involves first obtaining the desired cell range you wish to modify, and then setting the data. The relevant APIs and their descriptions are documented. Please review the documentation carefully before proceeding.
