### ISSUE TITLE
[Bug] Render a Word document based on the json data you provide, why can't the image be rendered?

### ISSUE THREAD

**Issue by ReturnToTheYouth** [dream-num/univer#4173]
### Before you submit this issue, have you checked the following

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Affected packages and versions

0.4.1

### Reproduction link

Hello, I directly use your data to run in my program, and the image is not rendered, please help me take a look? The codesandbox link：https://codesandbox.io/p/devbox/4v3jtm?file=%2Fsrc%2Fcomponents%2Fdoc%2FuniverDoc.vue%3A22%2C47

### Expected behavior

render the  image

### Actual behavior

not render image

### System information

 System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 1.00 GB / 15.68 GB
  Binaries:
    Node: 18.20.0 - D:\software\node\node-v18.20.0-win-x64\node.EXE
    Yarn: 1.22.22 - D:\software\node\node-v18.20.0-win-x64\yarn.CMD
    npm: 10.5.0 - D:\software\node\node-v18.20.0-win-x64\npm.CMD
    pnpm: 9.5.0 - D:\software\node\node-v18.20.0-win-x64\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355

**Comment by ReturnToTheYouth** [comment]
hello, installed drawing-related plugin.,reported some errors.,I haven't found a relevant solution at present.,Can you help take a look? link： https://codesandbox.io/p/devbox/4v3jtm?file=%2Fsrc%2Fcomponents%2Fdoc%2FuniverDoc.vue%3A82%2C40

**Comment by jikkai** [comment]
First, your demo is neither a minimal reproducible example nor does it have the correct dependencies installed. Additionally, your data is missing the critical `resources` field, where the drawing-related plugin information should be stored.

My suggestion is that, since you’ve already installed that plugins, you can simply upload a new image and save a snapshot to check the actual data structure.

This issue will now be locked.
